# Generated by Django 6.0.4 on 2026-04-22 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('last_trained', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
